apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP #clusterip , nodeport, Lodbalancer (public ip wbesite)
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port nginx