apiVersion: v1
kind: Service
metadata:
  name: front-endend-service
spec:
  type: ClusterIP #clusterip , nodeport, Lodbalancer (public ip wbesite)
  selector:
    app: front-end
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port nginx